name: API CI (Production)

on:
    push:
        branches: [main]

jobs:
    Integration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: yarn install
            - name: Integration tests
              run: yarn test:ci
            - name: Build
              run: yarn build
